### ISSUE TITLE
quit command raises JSON::ParseError

### ISSUE THREAD

**Issue by okkez** [ranguba/groonga-client#12]
Is this known issue?

```
$ groonga-client
quit
lib/ruby/gems/2.4.0/gems/json-2.0.3/lib/json/common.rb:156:in `parse': 409: unexpected token at 'true]' (JSON::ParserError)
        from lib/ruby/gems/2.4.0/gems/json-2.0.3/lib/json/common.rb:156:in `parse'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/response/base.rb:67:in `parse'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/response/base.rb:47:in `parse'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/command.rb:49:in `parse_raw_response'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/command.rb:35:in `block in execute'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/protocol/http/synchronous.rb:47:in `block in send'
        from lib/ruby/2.4.0/net/http.rb:877:in `start'
        from lib/ruby/2.4.0/net/http.rb:608:in `start'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/protocol/http/synchronous.rb:39:in `send'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/protocol/http.rb:42:in `send'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/command.rb:34:in `execute'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client.rb:276:in `execute_command'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client.rb:176:in `execute'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/cli.rb:220:in `run_command'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/cli.rb:174:in `block in create_command_parser'
        from lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:155:in `on_command'
        from lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:278:in `process_command'
        from lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:253:in `parse_line'
        from lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:216:in `block (2 levels) in consume_buffer'
        from lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:212:in `loop'
        from lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:212:in `block in consume_buffer'
        from lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:211:in `catch'
        from lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:211:in `consume_buffer'
        from lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:132:in `<<'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/cli.rb:162:in `<<'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/cli.rb:57:in `block in run'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/cli.rb:56:in `each_line'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/lib/groonga/client/cli.rb:56:in `run'
        from lib/ruby/gems/2.4.0/gems/groonga-client-0.4.2/bin/groonga-client:23:in `<top (required)>'
        from bin/groonga-client:22:in `load'
        from bin/groonga-client:22:in `<main>'
```

**Comment by kou** [comment]
It's a limitation of groonga-httpd. `quit` (and `shutdown`) stops groonga-httpd while groonga-httpd processes the request. So groonga-httpd can't return response.
(Shutdown by request isn't nginx way but we force to implement it. It may be better that we deny `quit and `shutdown` on groonga-httpd.)

**Comment by okkez** [comment]
Does `quit` command means that exit groonga-client process with no backtrace and error message?
I found following document:

http://groonga.org/ja/docs/reference/commands/quit.html

BTW, groonga-httpd 6.1.5 on my Debian sid does not shutdown with quit command from groonga-client.

```
$ sudo systemctl status groonga-httpd
● groonga-httpd.service - Groonga full text search HTTP server
   oaded: loaded (/lib/systemd/system/groonga-httpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-04-12 11:26:55 JST; 3h 52min ago
     Docs: http://groonga.org/docs/server/package.html#groonga-httpd
  Process: 20890 ExecStop=/usr/sbin/groonga-httpd -s stop (code=exited, status=0/SUCCESS)
  Process: 20895 ExecStart=/usr/sbin/groonga-httpd (code=exited, status=0/SUCCESS)
  Process: 20893 ExecStartPre=/bin/mkdir -p /var/log/groonga/httpd (code=exited, status=0/SUCCESS)
 Main PID: 20897 (groonga-httpd)
    Tasks: 2 (limit: 4915)
   Memory: 20.8M
      CPU: 151ms
   CGroup: /system.slice/groonga-httpd.service
           ├─20897 nginx: master process /usr/sbin/groonga-httpd
         └─20898 nginx: worker process

 4月 12 11:26:55 enerian systemd[1]: Starting Groonga full text search HTTP server...
 4月 12 11:26:55 enerian systemd[1]: Started Groonga full text search HTTP server.

$ groonga-client
quit
(snip backtrace)

$ sudo systemctl status groonga-httpd
● groonga-httpd.service - Groonga full text search HTTP server
   Loaded: loaded (/lib/systemd/system/groonga-httpd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2017-04-12 11:26:55 JST; 3h 53min ago
     Docs: http://groonga.org/docs/server/package.html#groonga-httpd
  Process: 20890 ExecStop=/usr/sbin/groonga-httpd -s stop (code=exited, status=0/SUCCESS)
  Process: 20895 ExecStart=/usr/sbin/groonga-httpd (code=exited, status=0/SUCCESS)
  Process: 20893 ExecStartPre=/bin/mkdir -p /var/log/groonga/httpd (code=exited, status=0/SUCCESS)
 Main PID: 20897 (groonga-httpd)
    Tasks: 2 (limit: 4915)
   Memory: 20.8M
      CPU: 151ms
   CGroup: /system.slice/groonga-httpd.service
           ├─20897 nginx: master process /usr/sbin/groonga-httpd
           └─20898 nginx: worker process

 4月 12 11:26:55 enerian systemd[1]: Starting Groonga full text search HTTP server...
 4月 12 11:26:55 enerian systemd[1]: Started Groonga full text search HTTP server.
```

**Comment by kou** [comment]
Ah, you're running groonga-httpd as root and using switch user feature.
In the case, groonga-httpd had a bug that invalid JSON. I've fixed it.

**Comment by okkez** [comment]
Thanks!
