### ISSUE TITLE
Failed to load a lot of records in a load command

### ISSUE THREAD

**Issue by okkez** [ranguba/groonga-client#29]
Failed to load dump.grn using following command.

```
$ groonga-client dump.grn
 (Groonga::Client::Protocol::Error)ib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/protocol/http/synchronous.rb:51:in `block in send': 413 Request Entity Too Large: <html>
<head><title>413 Request Entity Too Large</title></head>
<body bgcolor="white">
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.11.8</center>
</body>
</html>
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:877:in `start'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:608:in `start'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/protocol/http/synchronous.rb:39:in `send'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/protocol/http.rb:42:in `send'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/command.rb:34:in `execute'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client.rb:276:in `execute_command'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client.rb:176:in `execute'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:220:in `run_command'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:213:in `consume_load_values'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:185:in `block in create_command_parser'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:185:in `on_load_value'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:361:in `block in initialize_load_values_parser'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser/load-values-parser.rb:99:in `pop_container'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser/load-values-parser.rb:82:in `block in initialize_parser'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-stream-0.2.1/lib/json/stream/parser.rb:452:in `block in notify'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-stream-0.2.1/lib/json/stream/parser.rb:451:in `each'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-stream-0.2.1/lib/json/stream/parser.rb:451:in `notify'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-stream-0.2.1/lib/json/stream/parser.rb:469:in `end_container'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-stream-0.2.1/lib/json/stream/parser.rb:368:in `block in <<'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-stream-0.2.1/lib/json/stream/parser.rb:157:in `each_char'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/json-stream-0.2.1/lib/json/stream/parser.rb:157:in `<<'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser/load-values-parser.rb:41:in `block in <<'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser/load-values-parser.rb:38:in `catch'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser/load-values-parser.rb:38:in `<<'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:225:in `consume_load_values'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:214:in `block (2 levels) in consume_buffer'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:212:in `loop'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:212:in `block in consume_buffer'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:211:in `catch'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:211:in `consume_buffer'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-command-parser-1.0.9/lib/groonga/command/parser.rb:132:in `<<'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:162:in `<<'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:65:in `block (3 levels) in run'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:63:in `each_line'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:63:in `block (2 levels) in run'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:61:in `open'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:61:in `block in run'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:60:in `each'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/lib/groonga/client/cli.rb:60:in `run'
        from /home/kenji/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/groonga-client-0.5.0/bin/groonga-client:23:in `<top (required)>'
        from /home/kenji/.rbenv/versions/2.4.1/bin/groonga-client:22:in `load'
        from /home/kenji/.rbenv/versions/2.4.1/bin/groonga-client:22:in `<main>'
```

dump.grn includes load command about 10,000 records at once.

On the other hand, groonga command can load dump.grn successfully.

```
$ groonga -n /tmp/db --file=dump.grn
```

**Comment by kou** [comment]
It's caused by `client_max_body_size` configuration in `groonga-httpd.conf`.

We can resolve this by increase `client_max_body_size` or reducing one load chunk size by `groonga-client --split-load-chunk-size=100`.
